
export const SONG_SELECTED = 'SONG_SELECTED'
export const UPDATE_SELECTED = 'SONG_SELECTED'
export const SONG_FETCH = 'FETCH_SONG'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_ALL_USER = 'FETCH_ALL_USER'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const STEAMS_CREATE = 'STEAMS_CREATE'
export const STEAMS_EDIT = 'STEAMS_EDIT'
export const STEAMS_DELETE = 'STEAMS_DELETE'
export const STEAMS_FETCH = 'STEAMS_FETCH'
export const STEAMS_FETCH_ALL = 'STEAMS_FETCH_ALL'
// export const STEAMS_CREATE = 'SIGN_'
